import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/ui/theme-provider';
import type { ReactNode } from 'react';
import { GeistMono } from 'geist/font/mono';

export const metadata: Metadata = {
  title: 'Talha Codes',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={GeistMono.className}>
        <div className="relative">
          {/* Masked background overlay */}
          <div
            className="absolute inset-0 pointer-events-none bg-[linear-gradient(to_right,#7373732e_1px,transparent_1px),linear-gradient(to_bottom,#7373732e_1px,transparent_1px)] bg-[size:20px_20px] z-0"
            style={{
              maskImage:
                'radial-gradient(ellipse 80% 50% at 50% 50%, black 70%, transparent 110%)',
              WebkitMaskImage:
                'radial-gradient(ellipse 80% 50% at 50% 50%, black 70%, transparent 110%)',
            }}
          />

          {/* Main content */}
          <div className="relative z-10">
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange>
              {children}
            </ThemeProvider>
          </div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
